[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]

[test.workflows]
timeout = 1500
cpu = ["!da3_streaming"]
gpu = "all"

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true