[node_reqs]
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI-KJNodes = "kijai/ComfyUI-KJNodes"
ComfyUI-Env-Manager = "PozzettiAndrea/ComfyUI-Env-Manager"

[cuda]
packages = ["flash_attn", "sageattention"]