[test]
levels = ["syntax", "install", "registration", "execution"]

[test.workflows]
run = "all"
screenshot = "all"
timeout = 300
cpu = "all"
gpu = "all"

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true