[test]
levels = ["syntax", "install", "registration", "instantiation", "static_capture", "execution"]

[test.workflows]
timeout = 300
cpu = "all"
gpu = "all"

[test.platforms]
linux = false
macos = false
windows = false
windows_portable = false
linux_gpu = false
windows_gpu = false
windows_portable_gpu = false